import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  knowledgeBase: [
    'home',
    {
      type: 'category',
      label: 'TITAN Enterprise',
      items: [{type: 'autogenerated', dirName: 'platform'}],
    },
    {
      type: 'category',
      label: 'Products',
      items: [{type: 'autogenerated', dirName: 'products'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Missions',
      items: [{type: 'autogenerated', dirName: 'missions'}],
    },
    {
      type: 'category',
      label: 'Governance',
      items: [{type: 'autogenerated', dirName: 'governance'}],
    },
    {
      type: 'category',
      label: 'Security and Compliance',
      items: [{type: 'autogenerated', dirName: 'security'}],
    },
    {
      type: 'category',
      label: 'Quality Management',
      items: [{type: 'autogenerated', dirName: 'quality'}],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [{type: 'autogenerated', dirName: 'operations'}],
    },
  ],
};

export default sidebars;
