export enum ProgrammeGoalClassification {
    STRENGTH = "STRENGTH",
    HYPERTROPHY = "HYPERTROPHY",
    ENDURANCE = "ENDURANCE",
    SPEED = "SPEED",
    POWER = "POWER",
    MOBILITY = "MOBILITY",
    CONDITIONING = "CONDITIONING",
    GENERAL_FITNESS = "GENERAL_FITNESS",
    SPORT_PERFORMANCE = "SPORT_PERFORMANCE",
}
