import crypto from "node:crypto";
import request from "supertest";
import { describe, expect, it } from "vitest";

import app from "../../../src/app";

import { testPrisma } from "../../helpers/prisma-test.client";
import { createTestUser } from "../../factories/user.factory";


describe("Authentication Rate Limiting", () => {


    it(
        "enforces the authentication rate limit and persists RATE_LIMIT_EXCEEDED security event",
        async () => {

            const { user, password } =
                await createTestUser();


            const correlationId =
                crypto.randomUUID();


            const userAgent =
                `TITAN-045-AUTH-RATE-LIMIT-TEST-${correlationId}`;


            let rateLimitedResponse:
                request.Response | undefined;


            for (
                let attempt = 0;
                attempt < 10;
                attempt++
            ) {

                const response =
                    await request(app)
                        .post("/api/v1/auth/login")
                        .set(
                            "X-Request-Id",
                            `CLIENT-CONTROLLED-${crypto.randomUUID()}`,
                        )
                        .set(
                            "User-Agent",
                            userAgent,
                        )
                        .send({
                            tenantId:
                                user.tenantId,

                            email:
                                user.email,

                            password,
                        });


                if (response.status === 429) {

                    rateLimitedResponse =
                        response;

                    break;

                }

            }


            expect(
                rateLimitedResponse,
            ).toBeDefined();


            expect(
                rateLimitedResponse!.status,
            ).toBe(429);


            expect(
                rateLimitedResponse!.body,
            ).toMatchObject({

                error:
                    "Too Many Requests",

                message:
                    "Too many authentication attempts. Please try again later.",

            });


            expect(
                rateLimitedResponse!.headers[
                    "x-ratelimit-limit"
                ],
            ).toBe("3");


            expect(
                rateLimitedResponse!.headers[
                    "x-ratelimit-remaining"
                ],
            ).toBe("0");


            const securityEvents =
                await testPrisma.securityEvent.findMany({

                    where: {

                        eventType:
                            "RATE_LIMIT_EXCEEDED",

                        userAgent,

                    },

                    orderBy: {

                        createdAt:
                            "desc",

                    },

                });


            expect(
                securityEvents,
            ).toHaveLength(1);


            const securityEvent =
                securityEvents[0];


            expect(
                securityEvent.eventType,
            ).toBe(
                "RATE_LIMIT_EXCEEDED",
            );


            /*
             * Authentication has not yet occurred when the
             * auth rate limiter rejects the request.
             *
             * Therefore the security event must remain
             * anonymous rather than trusting client-supplied
             * identity data.
             */
            expect(
                securityEvent.tenantId,
            ).toBeNull();


            expect(
                securityEvent.userId,
            ).toBeNull();


            expect(
                securityEvent.userAgent,
            ).toBe(
                userAgent,
            );


            /*
             * The request ID must be generated by TITAN itself.
             * The caller-supplied X-Request-Id must never become
             * the persisted security-event request ID.
             */
            expect(
                securityEvent.requestId,
            ).toBeDefined();


            expect(
                securityEvent.requestId,
            ).not.toBeNull();


            expect(
                securityEvent.requestId,
            ).not.toBe("");


            expect(
                securityEvent.requestId,
            ).not.toContain(
                "CLIENT-CONTROLLED",
            );


            expect(
                securityEvent.ipAddress,
            ).toBeDefined();


            expect(
                securityEvent.ipAddress,
            ).not.toBeNull();


            const metadata =
                securityEvent.metadata as Record<
                    string,
                    unknown
                >;


            expect(
                metadata.method,
            ).toBe("POST");


            expect(
                metadata.path,
            ).toBe("/api/v1/auth/login");

        },
    );

});

