import express from "express";
import request from "supertest";

import {
    describe,
    expect,
    it,
} from "vitest";

import {
    createApiRateLimiter,
} from "../../../src/middleware/rate-limit.middleware";

import {
    requestIdMiddleware,
} from "../../../src/middleware/request-id.middleware";

import {
    requestContextMiddleware,
} from "../../../src/middleware/request-context.middleware";

import {
    rateLimitModule,
} from "../../../src/infrastructure/composition/rate-limit.module";

import {
    testPrisma,
} from "../../helpers/prisma-test.client";


describe("Rate Limit Security Events", () => {


    it(
        "persists RATE_LIMIT_EXCEEDED with server-generated security context",
        async () => {

            const app =
                express();


            app.use(
                requestIdMiddleware,
            );


            app.use(
                requestContextMiddleware,
            );


            app.use(
                createApiRateLimiter(
                    60 * 1000,
                    1,
                    rateLimitModule.recordRateLimitExceeded,
                ),
            );


            app.get(
                "/rate-limit-test",
                (_request, response) => {

                    response
                        .status(200)
                        .json({
                            success: true,
                        });

                },
            );


            /*
             * Unique test correlation value.
             *
             * This is deliberately placed in the User-Agent so the
             * persisted security event can be deterministically located
             * without relying on client-controlled request IDs.
             */
            const correlationId =
                crypto.randomUUID();


            const userAgent =
                `TITAN-RATE-LIMIT-INTEGRATION-TEST-${correlationId}`;


            /*
             * First request establishes the limiter bucket.
             */
            const first =
                await request(app)
                    .get("/rate-limit-test")
                    .set(
                        "User-Agent",
                        userAgent,
                    );


            expect(first.status)
                .toBe(200);


            /*
             * Second request exceeds the configured limit.
             */
            const second =
                await request(app)
                    .get("/rate-limit-test")
                    .set(
                        "User-Agent",
                        userAgent,
                    );


            expect(second.status)
                .toBe(429);


            expect(second.body)
                .toMatchObject({
                    error:
                        "Too Many Requests",

                    message:
                        "Rate limit exceeded. Please try again later.",
                });


            expect(
                second.headers["x-ratelimit-limit"],
            )
                .toBe("1");


            expect(
                second.headers["x-ratelimit-remaining"],
            )
                .toBe("0");


            /*
             * Query exclusively by the unique test User-Agent.
             *
             * Vitest matchers must never be embedded inside Prisma
             * query arguments.
             */
            const securityEvents =
                await testPrisma.securityEvent.findMany({

                    where: {
                        eventType:
                            "RATE_LIMIT_EXCEEDED",

                        userAgent,
                    },

                    orderBy: {
                        createdAt:
                            "desc",
                    },

                });


            expect(securityEvents)
                .toHaveLength(1);


            const securityEvent =
                securityEvents[0];


            /*
             * Event classification.
             */
            expect(
                securityEvent.eventType,
            )
                .toBe("RATE_LIMIT_EXCEEDED");


            /*
             * The request ID must be generated by TITAN itself.
             *
             * We deliberately do not trust a caller-provided X-Request-Id.
             */
            expect(
                securityEvent.requestId,
            )
                .toBeDefined();


            expect(
                securityEvent.requestId,
            )
                .not.toBeNull();


            expect(
                securityEvent.requestId,
            )
                .not.toBe("");


            expect(
                securityEvent.requestId,
            )
                .toMatch(
                    /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,
                );


            /*
             * Anonymous request context.
             */
            expect(
                securityEvent.tenantId,
            )
                .toBeNull();


            expect(
                securityEvent.userId,
            )
                .toBeNull();


            /*
             * Network/request context.
             */
            expect(
                securityEvent.userAgent,
            )
                .toBe(userAgent);


            expect(
                securityEvent.ipAddress,
            )
                .toBeDefined();


            expect(
                securityEvent.ipAddress,
            )
                .not.toBeNull();


            expect(
                securityEvent.ipAddress,
            )
                .not.toBe("");


            /*
             * Security-event metadata.
             */
            const metadata =
                securityEvent.metadata as Record<string, unknown>;


            expect(
                metadata.method,
            )
                .toBe("GET");


            expect(
                metadata.path,
            )
                .toBe("/rate-limit-test");

        },
    );


});

