export enum AuditAction {
    AUTH_SUCCESS = "AUTH_SUCCESS",
    AUTH_FAILURE = "AUTH_FAILURE",
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",
    ACCOUNT_UNLOCKED = "ACCOUNT_UNLOCKED",

    PERMISSION_DENIED = "PERMISSION_DENIED",

    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    PASSWORD_RESET = "PASSWORD_RESET",

    SESSION_CREATED = "SESSION_CREATED",
    SESSION_REFRESHED = "SESSION_REFRESHED",
    SESSION_REVOKED = "SESSION_REVOKED",

    USER_CREATE = "USER_CREATE",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",

    ROLE_CREATE = "ROLE_CREATE",
    ROLE_UPDATE = "ROLE_UPDATE",
    ROLE_DELETE = "ROLE_DELETE",

    PERMISSION_CREATE = "PERMISSION_CREATE",
    PERMISSION_UPDATE = "PERMISSION_UPDATE",
    PERMISSION_DELETE = "PERMISSION_DELETE",

    WORKOUT_PROGRAMME_PERFORMANCE_ADAPTATION =
        "WORKOUT_PROGRAMME_PERFORMANCE_ADAPTATION",
}
