export enum AuditResource {
    AUTHENTICATION = "AUTHENTICATION",

    AUTHORIZATION = "AUTHORIZATION",

    USER = "USER",

    ROLE = "ROLE",

    PERMISSION = "PERMISSION",

    SESSION = "SESSION",

    WORKOUT_PROGRAMME = "WORKOUT_PROGRAMME",
    PERFORMANCE_MEASUREMENT = "PERFORMANCE_MEASUREMENT",
}
