export enum SecurityEventType {

    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS",

    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE",

    AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE",

    INVALID_AUTH_HEADER = "INVALID_AUTH_HEADER",

    INVALID_TOKEN = "INVALID_TOKEN",

    TOKEN_EXPIRED = "TOKEN_EXPIRED",

    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",

    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

}
