export enum SecurityEventType {

    AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS",

    AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE",

    AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE",

    INVALID_AUTH_HEADER = "INVALID_AUTH_HEADER",

    INVALID_TOKEN = "INVALID_TOKEN",

    TOKEN_EXPIRED = "TOKEN_EXPIRED",

    ACCOUNT_LOCKED = "ACCOUNT_LOCKED",

    TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS",

    TOKEN_REFRESH_FAILURE = "TOKEN_REFRESH_FAILURE",

    TOKEN_REUSE_DETECTED = "TOKEN_REUSE_DETECTED",

    SESSION_REVOKED = "SESSION_REVOKED",

    SUSPICIOUS_ACTIVITY = "SUSPICIOUS_ACTIVITY",

    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",

}
